### ISSUE TITLE
"isPrime" implementation is wrong

### ISSUE THREAD

**Issue by Stanko** [bcherny/frontend-interview-questions#1]
Hello,
Thanks for putting this together, I was just browsing and noticed a bug in implementation of [isPrime](https://github.com/bcherny/frontend-interview-questions/blob/master/coding-easy/isPrime.js). It returns wrong results.

Try:
```
isPrime(9); // -> true
isPrime(21); // -> true
isPrime(25); // -> true
```

And none of these is prime. It will return true for any odd number, as you are skipping all of the odd number dividers (counter has a value of `2 + (n * 2)`) on the [line #17](https://github.com/bcherny/frontend-interview-questions/blob/master/coding-easy/isPrime.js#L17)
```
  for (let i = 2; i < Math.ceil(Math.sqrt(n)); i += 2) {
    if (n % i === 0) {
      return false
    }
  }
```

You just need to increment by 1 not by 2.

Cheers!

**Comment by bcherny** [comment]
Good catch - thanks @Stanko.
