### ISSUE TITLE
BinarySearchTree: wrong size() in example

### ISSUE THREAD

**Issue by art-in** [bcherny/frontend-interview-questions#10]
Original question
```
let tree = new BinarySearchTree
tree.add(1, 2, 3, 4)
tree.add(5)
tree.has(2)                           // true
tree.has(5)                           // true
tree.remove(3)                        // undefined
tree.size()                           // 3
```

Should be `tree.size()  // 4` (total number of nodes)  

Or maybe `tree.depth() // 3` (highest distance from root, in case it is not [self-balancing BST](https://en.wikipedia.org/wiki/Self-balancing_binary_search_tree))

**Comment by bcherny** [comment]
Typo - good catch @artin-phares!
