### ISSUE TITLE
URL link not opening.

### ISSUE THREAD

**Issue by abisekhsubedi** [bcherny/frontend-interview-questions#21]
URL links to  the question doesn't load.

**Comment by mandeeps708** [comment]
https://web.archive.org/web/20211028150427/https://performancejs.com/post/hde6d32/The-Best-Frontend-JavaScript-Interview-Questions-(Written-by-a-Frontend-Engineer)

**Comment by bcherny** [comment]
Fixed in https://github.com/bcherny/frontend-interview-questions/commit/6a9b450f9cf83c92be229b2e90c0078f208fc8f6

Thanks for the report!
