### ISSUE TITLE
The Link for questions isn't opening.

### ISSUE THREAD

**Issue by prachi09051999** [bcherny/frontend-interview-questions#22]
Since we want to try to solve the questions before reading the solution, could you please try to solve this issue?

<img width="1792" alt="Screenshot 2022-03-31 at 3 05 30 PM" src="https://user-images.githubusercontent.com/34397111/161025147-2a0dc1b7-8ccb-4460-9fab-81bcf79a11ad.png">

**Comment by mandeeps708** [comment]
@prachi09051999 
https://web.archive.org/web/20211028150427/https://performancejs.com/post/hde6d32/The-Best-Frontend-JavaScript-Interview-Questions-(Written-by-a-Frontend-Engineer)

**Comment by bcherny** [comment]
Fixed in https://github.com/bcherny/frontend-interview-questions/commit/6a9b450f9cf83c92be229b2e90c0078f208fc8f6

Thanks for the report!
