### ISSUE TITLE
assignDeep function fails when the object value contains date object.

### ISSUE THREAD

**Issue by yanCode** [bcherny/frontend-interview-questions#4]
As in, https://github.com/bcherny/frontend-interview-questions/blob/master/coding-intermediate/assignDeep.js

if you try to call it with `let s = assignDeep({a:1}, {b: new Date()})`, you get an object: {a:1, b: {}},  rather than {a:1, b: date object}. 

**The reason lies in:**

function isObject(a) { return typeof a === 'object' && a !== null}

if you try to call it as: isObject(new Date()), it returns true, therefore it going to be treated the date as an iterable object, I mean, it recursively call the assignDeep method on the date object.

however, during my tests,  `function isObject(a) { return typeof a === 'object' && a !== null&& Object.keys(a).length>0` , can be a good solution to check if this source[key] is an interable object.

**Comment by bcherny** [comment]
This is a legitimate bug. Instead of getting bogged down in a correct `isPlainObject()` implementation, I've updated the original blog post to constrain the problem to just numbers and plain objects. See discussion in the PR: https://github.com/bcherny/frontend-interview-questions/pull/5.
