### ISSUE TITLE
reverse: wont work with Unicode surrogate pairs

### ISSUE THREAD

**Issue by art-in** [bcherny/frontend-interview-questions#6]
Current implementation
``` javascript
function reverse(string) {
  let index = string.length - 1
  let result = ''
  while (index > -1) {
    result += string[index]
    index--
  }
  return result
}
```

same as this one (short and popular one)
``` javascript

function reverse(string) {
    return string.split('').reverse().join('');
}

```

Both wont work with with Unicode chars which length is more than 16 bit (surrogate pairs).  
Because both ```split('')``` and ```string[i]``` will address characters by 16 bit blocks, and so destroy Unicode pairs.

Ex.:
``` javascript
reverse('abc 🚀') // Error: expected '�� cba' to equal '🚀 cba'
```

Solution is es6 ```string[Symbol.iterator]``` via destructuring, which takes Unicode chars into account ([proof](http://jsbin.com/kupoqo/edit?js,console)):
``` javascript
function reverse(str) {
  return [...str].reverse().join('');
}
```

Probably you want to keep answers as transparent as possible and `split().reverse().join()` is too hack-ish for educational purposes. But maybe you can mention Unicode issue in the comment above the solution for people to know. Cheers.

**Comment by bcherny** [comment]
Thanks for the discussion @artin-phares - I linked this issue from the answers.
