### ISSUE TITLE
isBalanced: blog post issue in examples

### ISSUE THREAD

**Issue by art-in** [bcherny/frontend-interview-questions#7]
[Source test](https://github.com/bcherny/frontend-interview-questions/blob/master/coding-easy/isBalanced.js) on github is ok, but [blog post](https://performancejs.com/post/hde6d32/The-Best-List-of-Frontend-JavaScript-Interview-Questions) has issue:
```javascript
isBalanced('{}{}')                    // false
```
Should be `true`.

**Comment by bcherny** [comment]
Updated - thanks @artin-phares.
